sources:
  - name: raw
    schema: raw
    tables:
    - name: ports
      identifier: ports

    - name: regions
      identifier: regions

    - name: exchange_rates
      identifier: exchange_rates
      descriptions: "Exchange Rate of the each current w.r.t USD"

    - name: datapoints
      description: "Raw data points of the shipment from the shipping system."
      identifier: datapoints
      columns:
        - name: D_ID
          description: "The data point ID corresponds to shipment from the source system."
        - name: CREATED
          description: "The timestamp when the data point was created in the source system."
        - name: ORIGIN_PID
          description: "The ID of the origin port of the shipment."
        - name: DESTINATION_PID
          description: "The ID of the destination port of the shipment."
        - name: VALID_FROM
          description: "The date from which the data point is valid."
        - name: VALID_TO
          description: "The date until which the data point is valid."
        - name: COMPANY_ID
          description: "The ID of the company whose shipment is"
        - name: SUPPLIER_ID
          description: "The ID of the supplier who is shipping the Equipment(Container)."
        - name: EQUIPMENT_ID
          description: "The ID of the equipment also called container."

    - name: charges
      description: "Raw charges data from the source system."
      identifier: charges
      columns:
        - name: D_ID
          description: "The raw data point ID (Primary Key of Datapoints table)"
        - name: CURRENCY
          description: "The currency of the corresponding charge for different service"
        - name: CHARGE_VALUE
          description: "The value of the charge for different services."

  - name: final
    schema: final
    tables:
    - name: charges_aggregated  
      description: "Aggregated Avergae and Median Charge"
      columns:
        - name: estimation_date
          description: "The date for the estimation"
        - name: lane_id
          description: "The lane identifier, generated by concatenating origin_port_id, 0 and destination_port_id"
        - name: equipment_id
          description: "The equipment identifier"
        - name: avg_charge_usd
          description: "The average charge in USD"
        - name: median_charge_usd
          description: "The median charge in USD"
        - name: origin_port_id
          description: "The ID of the origin port"
        - name: origin_port_name
          description: "The name of the origin port"
        - name: origin_region_slug
          description: "The region slug of the origin port"
        - name: destination_port_id
          description: "The ID of the destination port"
        - name: destination_port_name
          description: "The name of the destination port"
        - name: destination_region_slug
          description: "The region slug of the destination port"
        - name: dq_ok
          description: "Data quality indicator, True if data meets quality criteria"